apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: todoapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todoapp
    spec:
      containers:
        - name: todoapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_HOST
              value: todoapp-mysql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
