apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secrets
stringData:
  SECRET_KEY: local-kubernetes-key
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
# for prod we could not store secrets in values.yaml, we should use external secret management system like HashiCorp Vault or AWS Secrets Manager