apiVersion: v1
kind: Service
metadata:
  name: todoapp
  labels:
    app.kubernetes.io/name: todoapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: todoapp
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
